### PR TITLE
Vs template

### PR DESCRIPTION
**Pull request by AmenJlili**
Visual Studio Add-in Template for VS 19 and 22

### CODE REVIEW

**Comment by AmenJlili** [comment]
1. Fixed typo in the description [here](https://github.com/BlueByteSystemsInc/PDMFramework/blob/0ea7d8b0aeb534d90ed2bae333e7e38dba482734/VSTemplate/VSExtension/source.extension.vsixmanifest#L6). Should SOLIDWORKS
2. Fix trust issue when adding new setup task page (item template): 
image
It is possible the extension needs to be signed. In case of singing, send me the snk file.
3. Increment to version 1.3 when done.

**Comment by AmenJlili** [comment]
Another issue for the TaskSetupPage.

1. When a task setup page is created from the item template, you should try to place it under Task\SetupPages folder if that folder exists.
2. TaskSetupPage is a generic class of T. The T should be replaced with an actual class that you create called TaskSetupPageViewModel. The class is placed the same location as the task setup page. If the user calls the setup page SettingsPage for example, the view model class (T) will be called SettingsPageViewModel. 
Here's the implementation of the class: 

 ```
public class TaskSetupPageViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        public void OnPropertyChanged([CallerMemberName]string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
```

**Comment by avdynut** [comment]
> 1. When a task setup page is created from the item template, you should try to place it under Task\SetupPages folder if that folder exists.

I suppose it can be a little confusing for end-users. Because usually the new item is added to a folder, that the user selects.

**Comment by AmenJlili** [comment]
Yup. That's true.  The idea is to add it to the existing setup pages folder because the template creates it.

If the user right-clicks on a random folder and adds the task setup page then definitely add it there.
If the user right-clicks on the project then add it to the task/setuppages folder.

**Comment by avdynut** [comment]
@AmenJlili After some research, I can tell you, that this cannot be easily implemented. We should interrupt the standard process of creating items and this may cause additional bugs. Because we have to handle many conditions, like checking folders, moving files, editing the project file, checking item names, and so on. I think there will be a lot more effort than benefits. So I would not recommend you to add this feature.

**Comment by AmenJlili** [comment]
@avdynut ok. Let's make sure the other points are adressed. Thanks

**Comment by avdynut** [comment]
@AmenJlili Please test v1.3.
As for TaskSetupPage trust issue, now the warning is not displayed. Maybe because .cs behind code is being opened instead of designer view.

**Comment by AmenJlili** [comment]
@avdynut : Tested. Good work.

**Pull request merged**
